# Generated by Django 4.0.2 on 2022-03-07 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
