# Generated by Django 4.0.2 on 2022-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_orders_amount_remove_orders_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
