# Generated by Django 4.0.2 on 2022-03-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimages'),
        ('carts', '0005_orders_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
