# Generated by Django 4.0.2 on 2022-03-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_orders_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
    ]
