# Generated by Django 4.0.2 on 2022-03-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_alter_orders_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash on delevery', 'cash on delevery'), ('Stripe', 'Stripe')], max_length=22)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=22)),
                ('payment_amount', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_ids', to='carts.orders')),
            ],
        ),
    ]
