# Generated by Django 4.0.2 on 2022-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_payment_user_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_secret_id',
            field=models.CharField(blank=True, max_length=122),
        ),
    ]
